# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ohci_pci" "ehci_pci" "uas" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8577c87c-9a65-4abb-b35a-fbe38bdb0627";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0604-8EE6";
      fsType = "vfat";
    };

  fileSystems."/mnt/nvd-raid" =
    { device = "/dev/disk/by-uuid/71e9b497-16ad-490a-a04f-75c47daa0840";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/410b48e2-1ab9-4f87-a271-c8fcb260f079"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
